/**
 * Upload marketing imagery to Cloudinary and emit a typed manifest.
 *
 * Site imagery (hero, trade tiles) doesn't belong to any artisan, so it goes
 * to a shared `site/` folder with a stable public_id rather than the
 * per-user folders artisan uploads use. A fixed public_id means re-running
 * this replaces the asset in place instead of piling up duplicates.
 *
 * Writes src/data/site-images.ts so the URLs are type-checked and swapping a
 * photo later is a one-line edit.
 *
 *   npm run upload:site-images -- config.json
 *
 * Config: [{ "key": "hero", "url": "https://...", "alt": "..." }]
 */

import { readFileSync, writeFileSync } from "node:fs";

import { config as loadEnv } from "dotenv";

loadEnv({ path: ".env.local" });
loadEnv({ path: ".env" });

type Entry = {
  key: string;
  url: string;
  alt: string;
  /**
   * Strip uniform borders before storing. Image generators often pad a
   * result to hit the requested aspect ratio, and those bars are invisible
   * in a thumbnail but obvious across a full-bleed hero.
   */
  trim?: boolean;
};

async function main() {
  const configPath = process.argv.slice(2).find((a) => !a.startsWith("--"));
  if (!configPath) {
    console.error("Usage: npm run upload:site-images -- config.json");
    process.exit(1);
  }

  const entries = JSON.parse(readFileSync(configPath, "utf8")) as Entry[];

  const { cloudinary } = await import("../src/lib/cloudinary");
  const { env, features } = await import("../src/lib/env");

  if (!features.cloudinary) {
    console.error("Cloudinary is not configured — check .env.local");
    process.exit(1);
  }

  const results: (Entry & { publicId: string; secureUrl: string; width: number; height: number })[] =
    [];

  for (const entry of entries) {
    const uploaded = await cloudinary.uploader.upload(entry.url, {
      folder: `${env.CLOUDINARY_UPLOAD_FOLDER}/site`,
      public_id: entry.key,
      overwrite: true,
      // No crop here — the layout decides framing via object-cover, and
      // baking a crop in would make re-use in another slot impossible.
      transformation: [
        ...(entry.trim ? [{ effect: "trim:10" }] : []),
        { width: 2000, crop: "limit" },
        { quality: "auto:good", fetch_format: "auto" },
      ],
    });

    results.push({
      ...entry,
      publicId: uploaded.public_id,
      secureUrl: uploaded.secure_url,
      width: uploaded.width,
      height: uploaded.height,
    });

    console.log(`  ✓ ${entry.key.padEnd(20)} ${uploaded.width}x${uploaded.height}`);
  }

  // Merge with whatever is already in the manifest rather than replacing it.
  // Source URLs are short-lived signed links, so re-uploading one image is a
  // normal thing to do — and it must not wipe the six that weren't touched.
  const existing = new Map<string, { url: string; alt: string; width: number; height: number }>();

  try {
    const current = readFileSync("src/data/site-images.ts", "utf8");
    const entryPattern =
      /"([\w-]+)":\s*\{\s*url:\s*"([^"]+)",\s*alt:\s*"([^"]*)",\s*width:\s*(\d+),\s*height:\s*(\d+),/g;
    for (const match of current.matchAll(entryPattern)) {
      existing.set(match[1]!, {
        url: match[2]!,
        alt: match[3]!,
        width: Number(match[4]),
        height: Number(match[5]),
      });
    }
  } catch {
    // First run — nothing to merge.
  }

  for (const r of results) {
    existing.set(r.key, {
      url: r.secureUrl,
      alt: r.alt,
      width: r.width,
      height: r.height,
    });
  }

  const merged = [...existing.entries()].sort(([a], [b]) => a.localeCompare(b));

  const file = `/**
 * Marketing imagery. Generated by scripts/upload-site-images.ts — edit that
 * script's config and re-run rather than hand-editing these URLs.
 *
 * Alt text is written as voice, not as a label: it is read aloud by screen
 * readers and shown when an image fails on a slow connection, which on
 * Nigerian mobile data is often.
 */

export type SiteImage = {
  url: string;
  alt: string;
  width: number;
  height: number;
};

export const SITE_IMAGES = {
${merged
  .map(
    ([key, v]) =>
      `  ${JSON.stringify(key)}: {\n    url: ${JSON.stringify(v.url)},\n    alt: ${JSON.stringify(v.alt)},\n    width: ${v.width},\n    height: ${v.height},\n  },`,
  )
  .join("\n")}
} as const satisfies Record<string, SiteImage>;

export type SiteImageKey = keyof typeof SITE_IMAGES;
`;

  writeFileSync("src/data/site-images.ts", file, "utf8");
  console.log("\n✓ wrote src/data/site-images.ts");
}

main().catch((error) => {
  console.error("\n✗ failed:", error);
  process.exit(1);
});
