/**
 * Marketing imagery. Generated by scripts/upload-site-images.ts — edit that
 * script's config and re-run rather than hand-editing these URLs.
 *
 * Alt text is written as voice, not as a label: it is read aloud by screen
 * readers and shown when an image fails on a slow connection, which on
 * Nigerian mobile data is often.
 */

export type SiteImage = {
  url: string;
  alt: string;
  width: number;
  height: number;
};

export const SITE_IMAGES = {
  "hero": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785676019/fixam/site/hero.jpg",
    alt: "An electrician working on a distribution board in a Lagos apartment, late afternoon light coming through the window",
    width: 1374,
    height: 768,
  },
  "trade-ac": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785675463/fixam/site/trade-ac.jpg",
    alt: "A technician servicing a wall-mounted split-unit air conditioner",
    width: 1024,
    height: 1024,
  },
  "trade-aluminium": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785676239/fixam/site/trade-aluminium.jpg",
    alt: "An aluminium fabricator measuring a window frame in his workshop",
    width: 1024,
    height: 1024,
  },
  "trade-carpenter": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785675462/fixam/site/trade-carpenter.jpg",
    alt: "A carpenter planing timber in a sunlit workshop, shavings curling from the blade",
    width: 1024,
    height: 1024,
  },
  "trade-generator": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785675467/fixam/site/trade-generator.jpg",
    alt: "A technician servicing a petrol generator outside a house",
    width: 1024,
    height: 1024,
  },
  "trade-painter": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785675466/fixam/site/trade-painter.jpg",
    alt: "A painter rolling fresh paint onto an interior wall",
    width: 1024,
    height: 1024,
  },
  "trade-plumber": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785675461/fixam/site/trade-plumber.jpg",
    alt: "A plumber's hands tightening a chrome fitting beneath a sink",
    width: 1024,
    height: 1024,
  },
  "trade-pop": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785675464/fixam/site/trade-pop.jpg",
    alt: "A craftsman smoothing plaster of paris cornice work along a ceiling",
    width: 1024,
    height: 1024,
  },
  "trade-tiler": {
    url: "https://res.cloudinary.com/v8xoeloe/image/upload/v1785676238/fixam/site/trade-tiler.jpg",
    alt: "A tiler kneeling to lay a large porcelain floor tile, spirit level beside him",
    width: 1024,
    height: 1024,
  },
} as const satisfies Record<string, SiteImage>;

export type SiteImageKey = keyof typeof SITE_IMAGES;
